sonar.projectKey=joandiazestigarribia_integration-status-dashboard
sonar.organization=joandiazestigarribia
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**
sonar.exclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Mantener igual que collectCoverageFrom en jest.config.ts.
sonar.coverage.exclusions=src/app/layout.tsx,src/app/page.tsx,src/components/ServiceWorkerRegister.tsx
sonar.qualitygate.wait=true
